### PR TITLE
Port to Pure Swift

### PR DESCRIPTION
**Pull request by ElvishJerricco**
These changes introduce no major API changes, or behavioral changes.

All Objective C code is removed and replaced with equivalent Swift code.

The Objective C code used a few Macros and dlsym hacks to work around
iOS 8+ dependency. Swift makes this easier with availability
constraints. No need for dlsym.

NS_ENUMs are ported directly to Swift enums.

NS_OPTIONS are ported to Swift OptionSetType structs.

A few types are changed from implicit optionals to non-optionals.

Various wrapper functions written in Objective C weren't necessary.

dk_dispatch_get_context and dk_dispatch_set_context are ported to
protocol extensions on DispatchObject. DispatchObject.getContext() and
setContext generalized this way, requiring implementors to instead just
provide a dispatch_object_t rawValue, which gets used by the ported
functions.

DispatchCookie is now a class protocol instead of an @objc protocol,
since @objc is no longer necessary.

DispatchQueueObject was completely unnecessary. Made more sense to just
have the DispatchQueue struct standalone.

### CODE REVIEW

**Comment by ElvishJerricco** [comment]
If pulled, I suggest making a v2.1 release tag. Git tags are how the Swift package manager finds the appropriate version.

**Comment by ElvishJerricco** [comment]
Actually, the Swift package manager requires Git release tags to be in [Semantic Versioning](http://semver.org) format. So the tag would have to be "2.1.0"

**Comment by ElvishJerricco** [comment]
In the interest of making this as modular as possible for the sake of the package manager, and eventual Linux support, I've moved some files around. This also made it easy to add an OS X target. So now it's fully cross platform, and supporting the package manager.

**Comment by anpol** [comment]
Committed with minor corrections. Thanks!

**Pull request closed without merging**
